apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-service
  labels:
    app: telemetry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
    spec:
      containers:
      - name: telemetry-service
        image: telemetry-service:latest
        imagePullPolicy: IFNotPresent
        envFrom:
        - configMapRef:
            name: telemetry-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
spec:
  selector:
    app: telemetry-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
